### ISSUE TITLE
Endpoint issue with some os packs

### ISSUE THREAD

**Issue by jbonjean** [savoirfairelinux/monitoring-tools#47]
- linux-cinder: `Arguments error: the argument cinder_endpoint must be present`
- linux-nova: `Arguments error: the argument nova_endpoint must be present`

The following custom fields are configured on my host: _OS_AUTH_URL, _OS_GLANCE_URL, _OS_CINDER_URL, _NOVA_URL, _OS_USERNAME, _OS_PASSWORD, _OS_TENANT_NAME.

Thanks.

**Comment by ReAzem** [comment]
linux-cinder used ``_OS_TENANT`` instead of ``_OS_TENANT_NAME``. I think this is what caused the issue.

Nova had a similar issue.
